# Generated by Django 5.0.7 on 2024-08-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.CharField(max_length=255, unique=True)),
                ('input_name', models.CharField(max_length=255)),
                ('input_email', models.EmailField(max_length=254)),
                ('input_cel_phone', models.CharField(max_length=50)),
                ('input_msg', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('cardholder_email', models.EmailField(max_length=254)),
                ('cardholder_name', models.CharField(max_length=255)),
                ('count_persons', models.IntegerField()),
                ('style_dessert', models.CharField(max_length=255)),
                ('savor_dessert', models.CharField(max_length=255)),
                ('filling', models.CharField(max_length=255)),
                ('dessert', models.CharField(max_length=255)),
                ('color_of_dessert', models.CharField(max_length=255)),
                ('color_of_border_dessert', models.CharField(max_length=255)),
                ('image_example_dessert', models.URLField(blank=True, null=True)),
                ('date_collect_dessert', models.DateField()),
                ('hour_collect_dessert', models.TimeField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method_id', models.CharField(max_length=255)),
            ],
        ),
    ]
