# Generated by Django 5.0.7 on 2024-08-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_collect_dessert',
            field=models.CharField(max_length=255),
        ),
    ]
