# Generated by Django 5.0.7 on 2024-08-17 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_purchase_cardholder_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
